### PR TITLE
terms and conditions

### PR DESCRIPTION
**Pull request by NotQuiteNicey**
adding the t&cs

### CODE REVIEW

**Comment by orbit-foundation** [comment]
### Response
We have found a bug in your code. A <script> tag has been used, followed by some JavaScript referring to popovers that aren't used. You have also not closed the <script> tag. Please update your code, and re-submit your code, quoting the PR code #1.

**Comment by NotQuiteNicey** [comment]
@pixelpro15 it is an embed code from onedrive

**Comment by orbit-foundation** [comment]
I am aware. It is not a JavaScript file however. We should also note that we can instead set it up to download the T&Cs from an <a> tag.

**Comment by orbit-foundation** [comment]
You have also, @Niceygy, imported multiple useless scripts from StackOverflow, JQuery, Bootstrap and other CDNs that you do not use.

**Pull request closed without merging**
